name: "Pod Operation Workflow"

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  lint-clippy:
    name: Lint Pod Operation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: clippy

      - name: Lint Rust
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  format:
    name: Format Pod Operation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt

      - name: Format Rust
        uses: actions-rs/rustfmt@v1

  build:
    name: Check Pod Operation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1

      - name: Build Pod Operation Program
        uses: actions-rs/cargo@v1
        with:
          command: build
