# Configuration to cross-compile for Raspberry Pi

[build]
target = "armv7-unknown-linux-gnueabihf"

[target.armv7-unknown-linux-gnueabihf]
# linker = "armv7-unknown-linux-gnueabihf-gcc"
linker = "arm-none-linux-gnueabihf-gcc"
