# Configuration to cross-compile for Raspberry Pi
# Uncomment lines as needed

[build]
target = "aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
# linker = "aarch64-unknown-linux-gnu-gcc"
linker = "aarch64-none-linux-gnu-gcc"
