name: "Control Station Workflow"

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  check-control-station:
    name: Check Control Station
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm install

      - name: Format with Prettier
        uses: EPMatt/reviewdog-action-prettier@v1
        with:
          level: warning
          reporter: github-pr-review
          prettier_flags: control-station/src

      - name: Lint with ESLint (review)
        uses: reviewdog/action-eslint@v1
        if: github.event_name == 'pull_request'
        with:
          level: error
          reporter: github-pr-review
          eslint_flags: control-station/src

      - name: Lint with ESLint (check)
        uses: reviewdog/action-eslint@v1
        if: github.event_name == 'push'
        with:
          workDir: control-station/
          level: error
          reporter: github-check
          eslint_flags: src

      - name: Test building
        run: npm run build
