name: "Pod Operation Workflow"

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  check-pod-operation:
    name: Check Pod Operation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pod-operation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Run cargo test
        run: cargo test

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Lint pod operation
        run: cargo clippy -- -D warnings

      - name: Build Pod Operation Program
        run: cargo build
