name: "Run Checks"

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  check-control-station:
    name: "Check Control Station"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./control-station
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm install

      - name: Format with Prettier
        uses: EPMatt/reviewdog-action-prettier@v1
        with:
          workdir: control-station/
          level: warning
          reporter: github-pr-review
          prettier_flags: src

      - name: Lint with ESLint (review)
        uses: reviewdog/action-eslint@v1
        if: github.event_name == 'pull_request'
        with:
          workdir: control-station/
          level: error
          reporter: github-pr-review
          eslint_flags: src

      - name: Lint with ESLint (check)
        uses: reviewdog/action-eslint@v1
        if: github.event_name == 'push'
        with:
          workDir: control-station/
          level: error
          reporter: github-check
          eslint_flags: src

      - name: Test building
        run: npm run build

  check-pod-operation:
    name: "Check Pod Operation"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pod-operation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Run cargo test
        run: cargo test

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Lint pod operation
        run: cargo clippy -- -D warnings

      - name: Build Pod Operation Program
        run: cargo build
